name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get the current date and time
      id: get_datetime
      run: echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Create and push tag
      env:
        DATETIME: ${{ env.DATETIME }}
      run: |
        TAG="v${DATETIME}"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git tag $TAG
        git push origin $TAG

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/newsdeployment:${{ env.DATETIME }}
